### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by asad-awadia** [YangDai2003/OpenNote-Compose#1]
Hello - thanks for the great app

I am using this as a base to add some extra functionality i need for my notes

I am trying to run this locally via android studio pixel 8 pro api 34 and it is impossible to run

It is extremely slow and constantly crashes - there is a lot of work being done on the main ui thread as well which i think should be moved but regardless

I wanted to ask if it is something you are seeing as well - or it is my side issue either my laptop is too slow or my virtual android device is not configured properly

How do you test and run this ?

@YangDai2003

**Comment by YangDai2003** [comment]
> Hello - thanks for the great app
> 
> I am using this as a base to add some extra functionality i need for my notes
> 
> I am trying to run this locally via android studio pixel 8 pro api 34 and it is impossible to run
> 
> It is extremely slow and constantly crashes - there is a lot of work being done on the main ui thread as well which i think should be moved but regardless
> 
> I wanted to ask if it is something you are seeing as well - or it is my side issue either my laptop is too slow or my virtual android device is not configured properly
> 
> How do you test and run this ?
> 
> @YangDai2003

Hello, 
first please make sure you git my latest version.
Since the application is still in its early stages, code updates will be frequent.

Secondly, I have tested on pixel virtual machines from api 29 to api 34, my Samsung mobile phone and firebase test lab, and there is no crash.

In addition, since the application adds firebase-related dependencies, please make sure you add your own google-services.json to the project, otherwise it will not work properly. If you do not have a firebase account, you need to remove the relevant dependencies.

It is worth mentioning that due to compose, the lag will be much more serious in debug mode than in release mode. Please refer to the actual release mode. I write all data-related operations in the viewmodel and execute them, and the main thread will not participate. As I wrote in the README.md file, the application adopts the MVVM architecture.

Of course, if you have any good improvements, you are more than welcome to make a pull request.
